version: 1.0.{build}
init:
- cmd: 
environment:
  matrix:
  - {}
services: mssql2016
install:
- cmd: 
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true
build:
  publish_wap: true
  publish_azure: true
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  parallel: true
  verbosity: normal
artifacts:
- path: www.circle.com
  name: Circle connected
  type: WebDeployPackage